module Civitas
  
  require_relative 'casilla.rb'
  require_relative 'casilla_calle.rb'
  require_relative 'casilla_impuesto.rb'
  require_relative 'casilla_juez.rb'
  require_relative 'casilla_sorpresa.rb'
  require_relative 'civitas_juego.rb'
  require_relative 'controlador.rb'
  require_relative 'dado.rb'
  require_relative 'diario.rb'
  require_relative 'estados_juego.rb'
  require_relative 'gestiones_inmobiliarias.rb'
  require_relative 'gestor_estados.rb'
  require_relative 'jugador.rb'
  require_relative 'jugador_especulador.rb'
  require_relative 'mazo_sorpresas.rb'
  require_relative 'operacion_inmobiliaria.rb'
  require_relative 'operaciones_juego.rb'
  require_relative 'respuestas.rb'
  require_relative 'salidas_carcel.rb'
  require_relative 'sorpresa.rb'
  require_relative 'sorpresa_especulador.rb'
  require_relative 'sorpresa_ir_carcel.rb'
  require_relative 'sorpresa_salir_carcel.rb'
  require_relative 'sorpresa_ir_casilla.rb'
  require_relative 'sorpresa_pagar_cobrar.rb'
  require_relative 'sorpresa_por_casa_hotel.rb'
  require_relative 'sorpresa_por_jugador.rb'
  require_relative 'tablero.rb'
  require_relative 'titulo_propiedad.rb'
  require_relative 'vista_textual.rb'
    
end
